server.port=8097
server.servlet.context.path= /dmaPayoutMaster

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB
server.tomcat.connection-timeout=300000
spring.mvc.async.request-timeout=300000


server.tomcat.max-swallow-size=-1
server.tomcat.max-http-form-post-size=-1

#server.servlet.session.timeout=30m
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
#logging.config=classpath:log4j2.properties
#logging.level.org.apache.jasper.servlet.TldScanner=OFF

#management.observations.enabled=false

#Oracle settings
#spring.datasource.url=jdbc:oracle:thin:@I00026L6CVD001.icicibankltd.com:9018:DBTRKDEV
#spring.datasource.username=DMA
#spring.datasource.password=DMA_123
#spring.datasource.driver.class=oracle.jdbc.driver.OracleDriver



#DMA UAT Oracle settings
#spring.datasource.url=jdbc:oracle:thin:@10.78.214.17:9017:DMAUAT
#spring.datasource.username=NUSER_7757
#spring.datasource.password=NUSER_7757_1234567
#spring.datasource.driver.class=oracle.jdbc.driver.OracleDriver

#cryptokey=U2VjcmV0IFBhc3NwaHJhc2U=

#JPA Config
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.Oracle12cDialect
spring.datasource.hikari.maximum-pool-size=30


# ===============================
# HIBERNATE BATCH SETTINGS
# ===============================
 
 
spring.jpa.properties.hibernate.jdbc.batch_size=500
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.jdbc.batch_versioned_data=true
spring.jpa.properties.hibernate.jdbc.fetch_size=100
spring.jpa.properties.hibernate.generate_statistics=false


#spring.jpa.show-sql=true
#logging.level.org.hibernate.type.descriptor.sql=TRACE
 
# ===============================
# HIKARI CONNECTION POOL
# ===============================
 
#spring.datasource.hikari.maximum-pool-size=40
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000


#JNDI settings
#spring.datasource.jndi-name=jdbc/HSAPP
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#
##Setting profiles
#spring.profiles.active=UAT
##spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
#
#
## HikariCP Settings
#spring.datasource.hikari.maximum-pool-size=50
#spring.datasource.hikari.minimum-idle=20
#spring.datasource.hikari.idle-timeout=30000
#spring.datasource.hikari.max-lifetime=1800000
#spring.datasource.hikari.pool-name=HikariCP
#
#server.tomcat.additional-headers=Content-Security-Policy: default-src 'self'; script-src 'self'; style-src 'self'
##New Add
#
#spring.main.allow-circular-references=true
#use.new.policy=N
# 
## Security Policies
##app.security.policy=default-src 'self'; frame-ancestors 'none'; script-src 'self'; style-src 'self'
#app.security.policy=default-src 'self'; frame-ancestors 'none'; script-src 'self'; style-src 'self'
## CORS Configuration
#cors.allowed.origins=*
#server.servlet.session.cookie.secure=true
#server.servlet.session.cookie.same-site=strict


spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=DMA
spring.datasource.password=DMA@123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.Oracle12cDialect

creditcard.files.basepath=D:/app/dma/CreditCard/